# Generated by Django 3.2.6 on 2021-11-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
    ]
