# Generated by Django 3.2.6 on 2021-11-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clientquote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientquote',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
