# Generated by Django 3.2.6 on 2021-11-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_phone_clientquote_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquote',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
