version: "3.8"
services:
  # Postgres Database
  postgres:
    container_name: headquarters_dev_postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env.staging

  # Django App
  backend:
    container_name: headquarters_dev_django
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env.staging
      - marketplace_api_key.env
    volumes:
      - ./backend:/backend
    command: /start.sh
    depends_on:
      - postgres

  # Frontend
  frontend:
    container_name: headquarters_dev_frontend
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend

volumes:
  postgres_data_dev:
