FROM node:latest

COPY ./frontend /frontend

WORKDIR /frontend

COPY ./frontend/package.json ./
COPY ./frontend/yarn.lock ./
RUN yarn install 
RUN yarn

# start app
CMD ["yarn", "start"]
# COPY ./docker_compose/node/development/start.sh /start.sh
# RUN sed -i 's/\r//' /start.sh
# RUN chmod +x /start.sh